### PR TITLE
Adding xterm's colourXXX color definitions

### PR DESCRIPTION
**Pull request by lnxbil**
Adding xterm-like color names from [1] and [2] as named RGB colors including a
simple test.

The marshaled color database has been changed as follows:
(I want do document this, because it was the hardest part of the commit):

1) unpack the marshalled file:

        f = File.open("rgb_colors.rb","w+")
        f.puts Marshal.load(Gem.gunzip(File.binread('rgb_colors.marshal.gz')))

2) prefix the unpacked file with 'RGB_COLOR ='
3) marshal the file again

        require './rgb_colors.rb'
        File.open("rgb_colors.marshal", "wb") do |file|
          Marshal.dump(RGB_COLORS,file)
        end

4) gzip the output and run the tests

[1] http://vim.wikia.com/wiki/Xterm256_color_names_for_console_Vim
[2] http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html

### CODE REVIEW

**Comment by lnxbil** [comment]
Sorry, for the "after pull-request" commits, but I run into trouble in my app and thought, let's fix it upstream.

**Comment by janlelis** [comment]
Hey lnxbil,

thank you for this PR and I am positive about getting your enhancements into the gem. However, I have some minor remarks:

- New color names: Instead of **colour** I'd prefer the prefix **xterm** (e.g. `xterm19`)
- Although I can see the convenience of the automatic 0 padding code, it adds more runtime-processing, which I want to avoid. To keep it consistent with already existing color names, I'd say lets only bundle the non-padded versions (e.g. `xterm19`)

Btw, I agree with you, updating the database is not well documented. These are the steps I use to manipulate it:

- Reading (like you did, but using the result directly in Ruby):
```ruby
db = Marshal.load(Gem.gunzip(File.binread('rgb_colors.marshal.gz')))
```

- *Updating the Hash*

- Writing:
```ruby
File.write('rgb_colors_new.marshal.gz', Gem.gzip(Marshal.dump(db)))
```

**Comment by lnxbil** [comment]
The color names are taken from tmux and I used the gem to format tmux statusbar, hence the names and the strange zero-prefix stuff. I removed the zero padding and changed the color names. Please check if it fits.

**Comment by janlelis** [comment]
One last thing then I'll merge it: `xterm` -> `xterm0`

**Pull request closed without merging**
